package com.foodtrackerbe.foodtrackerbe;

import java.util.ArrayList;
import java.time.LocalDate;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

// To fix the CORS error, allow local FE to access local backend
@CrossOrigin(origins = "http://localhost:4200", maxAge = 3600)
// @CrossOrigin(origins =
// "http://food-tracker-fe-dev.s3-website.us-east-2.amazonaws.com", maxAge =
// 3600)
// testing branching
@RestController
public class FoodController {

    @Autowired
    FoodServiceImpl foodService;

    @Autowired
    UserInfoServiceImpl userInfoService;

    // example: /food?id=320027
    // example: /food?name=Hummus
    // example: /food => will return empty list
    @RequestMapping(value = "/food", method = RequestMethod.GET)
    public List<FoodInfo> getFoodList(@RequestParam(required = false) Integer id, String name) {
        if (id != null) {
            return foodService.getFoodNutritions(id);
        } else if (name != null) {
            return foodService.searchFoodByName(name);
        }
        return new ArrayList<FoodInfo>();
    }

    // example: /userrecord?date=2020-10-20&userId=johnpark
    // date being passed in as a string "2020-10-20"
    @RequestMapping(value = "/userrecord", method = RequestMethod.GET)
    public List<UserInfo> getUserInfo(@RequestParam String date, String userId) {
        LocalDate convertedDate = LocalDate.parse(date);
        return userInfoService.getUserInfo(convertedDate, userId);
    }

    // example: /userrecord
    // Body:
    // [
    // {
    // "recordId": 0, //recordId will be auto-generated by DB, pass any number
    // "recordDate": "2020-10-10",
    // "userId": "johnmark",
    // "foodId": 320000,
    // "quantity": 2
    // },
    // {
    // "recordId": 0, //recordId will be auto-generated by DB, pass any number
    // "recordDate": "2020-10-10",
    // "userId": "johnmark",
    // "foodId": 456778,
    // "quantity": 1
    // }
    // ]
    @PostMapping("/userrecord")
    public void updateUserInfo(@RequestBody List<UserInfo> list) {
        userInfoService.saveUserInfo(list);
    }
}
